

services:
  backend:
    build: ./server
    container_name: flux-backend
    ports:
      - "8080:8080"
    restart: unless-stopped

  frontend:
    build: ./client
    container_name: flux-frontend
    ports:
      - "5173:5173"
    depends_on: 
      - backend
    restart: unless-stopped